# Generated by Django 4.0.5 on 2022-06-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuitModelCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretensao', models.CharField(max_length=1000)),
                ('requisitos_documentais', models.CharField(max_length=1000)),
                ('nome_peca', models.CharField(max_length=1000)),
                ('causa_pedir', models.CharField(max_length=1000)),
                ('pediso', models.CharField(max_length=1000)),
                ('beneficios', models.CharField(max_length=1000)),
                ('partes_processo', models.CharField(max_length=500)),
                ('terceiros', models.CharField(max_length=500)),
                ('cometencia', models.CharField(max_length=200)),
                ('equipe', models.CharField(max_length=500)),
                ('provas', models.CharField(max_length=1000)),
                ('entregas_processuais', models.CharField(max_length=1000)),
                ('restricoes', models.CharField(max_length=1000)),
                ('riscos', models.CharField(max_length=1000)),
                ('prazos', models.CharField(max_length=1000)),
                ('honorarios', models.CharField(max_length=500)),
                ('demais_despesas', models.CharField(max_length=1000)),
            ],
        ),
    ]
