# Generated by Django 4.0.5 on 2022-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitmodelcanvas',
            name='ementa',
            field=models.CharField(default='Ementa', max_length=3000),
            preserve_default=False,
        ),
    ]
