# Generated by Django 4.0.5 on 2022-07-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_suitmodelcanvas_ementa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitmodelcanvas',
            old_name='pediso',
            new_name='pedidos',
        ),
    ]
