# Generated by Django 4.0.5 on 2022-07-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_rename_pediso_suitmodelcanvas_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitmodelcanvas',
            old_name='cometencia',
            new_name='competencia',
        ),
    ]
